### ISSUE TITLE
medium和hard难度跨度范围太大，希望有更精确的难度标准

### ISSUE THREAD

**Issue by qixiabanyi** [KhasAlushird/nonebot_plugin_leetcodeAPI_KHASA#1]
![屏幕截图 2024-11-23 010015](https://github.com/user-attachments/assets/b0233b83-2762-43a6-8a7d-b522d1c287a4)

**Comment by KhasAlushird** [comment]
非常抱歉，leetcode的官方难度评级我无法变动......
